from fastapi import FastAPI
from typing import List, Dict
from engine.orchestrator import run_pipeline

app = FastAPI()


@app.get("/")
def health():
    return {"status": "ok"}


@app.post("/diagnose")
def diagnose(events: List[Dict]):
    result = run_pipeline(events)

    return {
        "root_causes": result[:5],
        "confidence": "probabilistic",
        "explanation": "Generated by AugurNet MVP"
    }
@app.get("/graph")
def get_graph():
    return {
        "nodes": [{"id": "A"}, {"id": "B"}],
        "links": [{"source": "A", "target": "B"}]
    }